AWSTemplateFormatVersion: 2010-09-09
Description: Create a VPC and an assumable role for cross account VPC peering.
# Parameters:
#   PeerRequesterAccountId:
#     Type: "512121751697"
Parameters:
  PrivateVPCIDCIDRRange:
    Description: The IP address range for your new Private VPC.
    Type: String
    MinLength: '9'
    MaxLength: '18'
    # Default: 10.0.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  # vpc:
  #   Type: 'AWS::EC2::VPC'
  #   Properties:
  #     CidrBlock: 172.31.0.0/16
  #     EnableDnsSupport: false
  #     EnableDnsHostnames: false
  #     InstanceTenancy: default
  # peerRole:
  #   Type: 'AWS::IAM::Role'
  #   Properties:
  #     AssumeRolePolicyDocument:
  #       Statement:
  #         - Principal:
  #             AWS: "086900803177"   #requester account id
  #           Action:
  #             - 'sts:AssumeRole'
  #           Effect: Allow
  #     Path: /
  #     Policies:
  #       - PolicyName: root
  #         PolicyDocument:
  #           Version: 2012-10-17
  #           Statement:
  #             - Effect: Allow
  #               Action: 'ec2:AcceptVpcPeeringConnection'
  #               Resource: '*'

  PeeringRoute2:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref PrivateVPCIDCIDRRange
      RouteTableId: !ImportValue network1-PrivateRouteTableID
      VpcPeeringConnectionId: !Ref vpcPeeringConnection
  PeeringRoute1:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 172.31.0.0/16 # 0.0.0.0/0
      RouteTableId: !ImportValue network1-PrivateRouteTableID
      VpcPeeringConnectionId: !Ref vpcPeeringConnection
    #Peering connection            
  vpcPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: vpc-0398eb88fd5272131     # requester vpc id
      PeerVpcId: vpc-0c967871   # accepter vpc id
      PeerOwnerId: "512121751697"    # accepter aws account id
      PeerRoleArn: arn:aws:iam::512121751697:role/Fox2021Peering-peerRole-15CR6ELC3MEPR             
Outputs:
  # VPCId:
  #   Value: !Ref vpc
  # RoleARN:
  #   Value: !GetAtt 
  #     - peerRole
  #     - Arn
  VPCPeeringConnectionId:
    Value: !Ref vpcPeeringConnection