Parameters:
  Password:
    NoEcho: 'true'
    Type: String
    Description: New account password
    MinLength: '1'
    MaxLength: '41'
    ConstraintDescription: the password must be between 1 and 41 characters
  
Resources:
  Usergroup1:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: FoxUsergroup
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::086900803177:policy/billing-policy
  Users1:
    Type: AWS::IAM::User
    Properties: 
      Groups: 
      - !Ref 'Usergroup1'
      LoginProfile: 
        Password: !Ref 'Password'
        PasswordResetRequired: 'true'
      UserName: soho
  Addusers1:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: !Ref 'Usergroup1'
      Users: 
        - !Ref 'Users1'

  Usergroup2:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: NAS-Financial-Group-Security-Team
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AdministratorAccess
  Users2:
    Type: AWS::IAM::User
    Properties: 
      Groups: 
      - !Ref 'Usergroup2'
      LoginProfile: 
        Password: !Ref 'Password'
        PasswordResetRequired: 'true'
      UserName: idriss   
  Addusers2:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: !Ref 'Usergroup2'
      Users: 
        - !Ref 'Users2'

  Usergroup3:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: NAS-Financial-Group-Operations-Team
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::086900803177:policy/us-east-1
        - arn:aws:iam::086900803177:policy/billing-policy
  Users3:
    Type: AWS::IAM::User
    Properties: 
      Groups: 
      - !Ref 'Usergroup3'
      LoginProfile: 
        Password: !Ref 'Password'
        PasswordResetRequired: 'true'
      UserName: claudio 
  Addusers3:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: !Ref 'Usergroup3'
      Users: 
        - !Ref 'Users3'

  Keypairs:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref Users1
         
Outputs:
  AccessKey:
    Value: !Ref 'Keypairs'
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [Keypairs, SecretAccessKey]
    Description: AWSSecretAccessKey of new user