Resources:
  PublicWebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP and SSH ingress
      VpcId: !ImportValue Network-template-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 72.83.17.230/32
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0

  PrivateWebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP and SSH ingress
      VpcId: !ImportValue Network-template-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 72.83.17.230/32


Outputs:
  PublicWebServerSecurityGroup:
    Description: The security group ID to use for public web servers
    Value: !GetAtt 
      - PublicWebServerSecurityGroup
      - GroupId
    Export:
      Name: !Sub '${AWS::StackName}-publicSecurityGroupID'

  PrivateWebServerSecurityGroup:
    Description: The security group ID to use for public web servers
    Value: !GetAtt 
      - PrivateWebServerSecurityGroup
      - GroupId
    Export:
      Name: !Sub '${AWS::StackName}-privateSecurityGroupID'